
server:
  port: 7003
spring:
  mvc:
    pathmatch:
#      knife4j匹配
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-2vc8850942200v94mpo.mysql.cn-chengdu.rds.aliyuncs.com:3306/submission.collect?useSSL=false
      username: root
      password: Iwillbethebest1029&&
  redis:
    host: 47.108.53.218
    port: 6379
    database: 1
  data:
    mongodb:
      host: 47.108.53.218
      port: 27017
      database: submission
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


mybatis-plus:
  global-config:
    db-config:
      id-type: assign_uuid
  mapper-locations:
    - classpath:mapper/*.xml




# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-head: true
